### PR TITLE
Get rid of camera lock on flag holder (optional)

### PR DESCRIPTION
**Pull request by suVrik**
Added the ability in netplay to play without camera lock on flag holder (it was very annoying in vanilla game, Frozlunky and Steam Remote Play). It can be enabled via a checkbox in netplay menu. Players out of the screen don't die in this mode by timeout (would break the net sync, both players would see their friends die out of their screens). Player ghosts could add some synchronization issues, so I disabled them too.
Fixed some memory issues.
Made it to compile against vcpkg libraries (for quick install, rather than messing with each library separately).
Removed resource references, because they are not included.
In release build I have rare crashes on startup. Could be some thirdparty from vcpkg, I don't think my code could do that... One time I also encountered players to be out of sync, but that also happened to me quite a few times in vanilla Frozlunky before my patch.
Thank you very much for Frozlunky! It is a lot of fun!

### CODE REVIEW

**Comment by sasha-volokh** [comment]
This is really impressive, thank you for this work! I'll test/merge this as soon as I can.

**Comment by sashavol** [comment]
This is really impressive, thank you for this work! I'll test/merge this as soon as I can.

**Comment by suVrik** [comment]
I'm happy to hear that! Feel free to comment on the code.

**Comment by sashavol** [comment]
I've merged this feature into master and corrected the resource file issue, this feature should now be available from the latest release of Frozlunky.

**Pull request merged**
